# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 778930abf2a1413bad8bcb066b72ff4988660fc7f31e5038928e5c386db7e72b36d6f5940b61758e4d690605aa1e9d853b47a281d61ebcfb2a94fe2a75a7b6da

test:
  secret_key_base: dee9fb69ade7e7d04760430617ab74f675d88be77b01dd8b6ef7cf3c220947970f756b085f3c351347ed72ef754c75b9c807ea9d25a4abd3388e3462cc9ab2f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
